rabbitmq:
  host: localhost
  username: guest
  password: guest
  port: 5672
  topicExchangeConfig:
    exchangeName: topic-exchange
    queueName: topic-queue
    routingKey: routing.key
  directExchangeConfig:
    exchangeName: direct-exchange
    queueName: direct-queue
    routingKey: routing.key
  fanoutExchangeConfig:
    exchangeName: fanout-exchange
    queue1: fanout-queue1
    queue2: fanout-queue2
    queue3: fanout-queue3
spring:
  data:
    mongodb:
      database: order-details
      port: 27017
      host: localhost
server:
  servlet:
    context-path: /consumer
