rabbitmq:
  host: localhost
  username: guest
  password: guest
  port: 5672
  topicExchangeConfig:
    exchangeName: topic-exchange
    queueName: topic-queue
    routingKey: routing.key
  directExchangeConfig:
    exchangeName: direct-exchange
    queueName: direct-queue
    routingKey: routing.key
  fanoutExchangeConfig:
    exchangeName: fanout-exchange
    queueName: fanout-queue
